### ISSUE TITLE
Trailing comma on file Composer.js

### ISSUE THREAD

**Issue by franciscoernestoteixeira** [planetfederal/GeoExplorer#15]
This trailing comma on file Composer.js is occurring a error on build, it is on line 114 at column 63:

code with error:
[code]
, {
                ptype: "gxp_googleearth",
                actionTarget: {target: "paneltbar", index: 17},
            }
[/code]

fixed code:
[code]
, {
                ptype: "gxp_googleearth",
                actionTarget: {target: "paneltbar", index: 17}
            }
[/code]

thanks!

**Comment by ahocevar** [comment]
Thanks for the report. Fixed with 87918e6841bc5f5df784a12ef0ba7a65f3222a2c
