### ISSUE TITLE
GeoExplorer legend does not use workspace in request

### ISSUE THREAD

**Issue by bosth** [planetfederal/GeoExplorer#28]
The legend in GeoExplorer does a GetLengendGraphic without specifying the workspace, so if there are two layers with the same name in different workspaces, the default workspace will be used even if the map is displaying the other layer.

**Comment by bartvde** [comment]
confirmed this is an issue indeed

**Comment by bartvde** [comment]
but this is really a GeoServer issue instead

http://sfmta.demo.opengeo.org/geoserver/wms?service=WMS&request=GetCapabilities

```
<LegendURL width="20" height="20">
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://sfmta.demo.opengeo.org:80/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=states"/>
</LegendURL>
```

we just take it from there.

**Comment by bosth** [comment]
GeoServer ticket: http://jira.codehaus.org/browse/GEOS-6758
