### ISSUE TITLE
SQLLITE DB issue

### ISSUE THREAD

**Issue by robertdbuckley** [planetfederal/GeoExplorer#4]
Hi,

i installed GeoExplorer as instructed from the Readme.txt. All the tests were past be "ant" and the WEB-INF Directory was created ok. Now it seems that the geoexplorer database which contains the saved maps hasn´t been created.

Is there anyway I can maybe do this manually and see if the save function will work? The error is firebug is 

"...
too much recursion
[Break On This Error](function%28%29{var h=Ext.util,j=Ext.each,...lclick",this.onNodeDblClick,this)}}); 

.."

I have no idea what this means..!!

great app otherwise and much improved. For the first time the editing functions work brilliantly! a great improvement from last year.

All the best,

Rob

**Comment by bartvde** [comment]
Rob, I am guessing you don't have this issue anymore, so closing. Please reopen if this is not true.

**Comment by robertdbuckley** [comment]
True!

I think this was either a permissions problem or something to do with setting the data_dir environment variable. It is now workin for me on my machine.Thanks for the help.

Rob
