### ISSUE TITLE
fatal error: gxp

### ISSUE THREAD

**Issue by robertdbuckley** [planetfederal/GeoExplorer#5]
I'm  getting this error when I  "ant init"

[exec] Submodule 'app/static/externals/gxp' (git://github.com/opengeo/gxp.git) registered for path 'app/static/externals/gxp'

The path seems ok, but after the build, the gxp directory is empty.

Cheers,

R Buckley

**Comment by bartvde** [comment]
This was a temporary glitch, build is working again so closing.

**Comment by robertdbuckley** [comment]
This also worked for me this week, so no problems now!
