### ISSUE TITLE
GeoExplorer build failed

### ISSUE THREAD

**Issue by girishneelath** [planetfederal/GeoExplorer#6]
I was trying to build geoexplorer from git. But it failed with an error

```
 [exec] fatal: reference is not a tree: 338bb94c34a3583a70c448e6d6b5cee50fa14c33
 [exec] Unable to checkout '338bb94c34a3583a70c448e6d6b5cee50fa14c33' in submodule path 'app/static/externals/gxp'
```

BUILD FAILED
/var/lib/tomcat6/webapps/GeoExplorer/build.xml:21: exec returned: 1

I feel the commit code for gxp in Geoexplorer is given as 338bb94c34a3583a70c448e6d6b5cee50fa14c33, But that does'nt exist. When i check gxp code, the latest commit number was 41be69feb603ec16b02b. I guess this was causing the build to fail. Hope the issue will be resolved soon.

**Comment by jamesboehmer** [comment]
Same issue here.  Can the externals be fixed, or rolled back?

**Comment by jamesboehmer** [comment]
Works now after the last two commits.  We're back in business.  Thanks!
